config/routes.rb
ClassMngmnt::Application.routes.draw do
  devise_for :students
  resources :students

  get '/hello', to: 'hello#hi'

  root to: "students#index"

end

app/models/course.rb
class Course < ActiveRecord::Base
  #belongs_to :student
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :student_courses
  has_many :courses, through: :student_courses

  validates :email, presence: true, uniqueness: true
  #validates_presence_of :email
end

app/models/student_course.rb
class StudentCourse < ActiveRecord::Base
  belongs_to :student 
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #layout 'hello'
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

  def hi

    respond_to do |format|
      format.html 
      format.json {render json: "Hello world!"}
      format.xml {redirect_to '/404'}
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html
      format.json {render json: @students.to_json}
      format.xml {render xml: @students.to_xml}
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:full_name, :bio, :age, :title, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def shorten_bio bio
    #word_wrap(bio, line_width: 40).gsub("\n", '<br/>').html_safe
    #truncate(bio, length: 40)
  end

  def shorten_bio bio
    truncate(bio,length:40).gsub("...",long_bio_tooltip(bio)).html_safe 
  end 

  def long_bio_tooltip bio 
    "<a title='#{bio.gsub("'","&apos;")}'>[+]</a>".html_safe 
  end

end

app/views/hello/hi.html.erb
<h1>Hello the time is: <%= Time.now %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassMngmnt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_student %>
You are logged in as: <%= current_student.email %>
<%= link_to 'Logout', destroy_student_session_path, method: :delete %>
<% else %>
<%= link_to 'Login', new_student_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/hello.html.erb
HI
<%= yield %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>All Students</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
<!--       <th>Bio</th>
      <th>Age</th> -->
      <th>Title</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.full_name, student %></td>
<!--         <td><%# shorten_bio student.bio %></td>
        <td><%# student.age %></td> -->
        <td><%= student.title %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @student.full_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= shorten_bio @student.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Title:</strong>
  <%= @student.title %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>